[environment]
python = "./.venv"
root = [
    "./barks-cmds",
    "./barks-restore",
    "./build-comics",
    "./scripts",
]

[src]
exclude = [
    "barks-restore/experiments/*.py",
    "build-comics/scraps/*.py",
    "barks-cmds/silent-night-panel-restore.py",
    "build-comics/scraps",
]
