extra:
  sys_name: ext://__main__.APP_LOGGING_NAME

handlers:
  - sink: ext://sys.stdout
    level: ext://__main__.log_level
    format: ext://comic_utils.loguru_setup.log_to_console_formatter
    enqueue: True
    backtrace: True
    diagnose: True
  - sink: fmt://{env://HOME}/Prj/github/barks-compleat-digital/barks-comic-building/logs/scripts.log
    level: "DEBUG"
    format: ext://comic_utils.loguru_setup.log_to_file_formatter
    rotation: "10 MB"
    enqueue: True
    backtrace: True
    diagnose: True
